#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [[ $1 == 'devserver' ]]; then
  python /app/manage.py migrate --noinput
  python /app/manage.py collectstatic --noinput
  python /app/manage.py load_config
  python /app/manage.py runserver_plus 0.0.0.0:8000 --insecure
elif [[ $1 == 'gunicorn' ]]; then
  python /app/manage.py migrate --noinput
  python /app/manage.py collectstatic --noinput
  python /app/manage.py load_config
  gunicorn liveconfigs_example.wsgi --chdir=/app \
    --bind 0.0.0.0:8000 \
    --workers="$GUNICORN_NUM_WORKERS" \
    --threads="$GUNICORN_NUM_THREADS" \
    --worker-class=gthread
elif [[ $1 == 'uvicorn' ]]; then
  python /app/manage.py migrate --noinput
  python /app/manage.py collectstatic --noinput
  python /app/manage.py load_config
  uvicorn liveconfigs_example.asgi:application --workers 1 --host 0.0.0.0 --port 8000
    # --chdir=/app \
    # --bind 0.0.0.0:8000 \
    # --workers="$GUNICORN_NUM_WORKERS" \
    # --threads="$GUNICORN_NUM_THREADS" \
    # --worker-class=gthread
elif [[ $1 == "celery_quick" ]]; then
  celery -A celery_app worker -n "${CELERY_WORKER_NAME}_quick" --loglevel=INFO -Q quick,notify,celery
elif [[ $1 == "celery_beat" ]]; then
  rm -rf celerybeat.pid
  celery -A celery_app purge -f -Q beat
  celery -A celery_app beat --loglevel=DEBUG
fi
